<?php

namespace Elegasoft\Cipher\Tests\Feature;

use Elegasoft\Cipher\Ciphers\Base62Cipher;
use Elegasoft\Cipher\Ciphers\Base96Cipher;
use Elegasoft\Cipher\Tests\TestCase;
use Illuminate\Support\Str;

class ManualTest extends TestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->markTestSkipped();
    }

    public function readMeExamples()
    {
        $cipher = new Base62Cipher(config('ciphers.keys.base62'));
        $code62 = $cipher->encipher('hide-this-number-1111');
        $cipher = new Base96Cipher(config('ciphers.keys.base96'));
        $code96 = $cipher->encipher('hide-this-number-1111');
        dd($code62, $code96);
    }

    public function setCipher(): void
    {
        $this->encoder = new Base62Cipher(config('ciphers.keys.base62'));
        $this->decoder = clone $this->encoder;
    }

    public function it_has_perfect_cipher_accuracy()
    {
    }

    public function it_can_work_on_a_specific_problem()
    {
        $this->markTestSkipped();
        $test = [];
        foreach (range(1000, 1010) as $id)
        {
            $padded = str_pad($id, 6, '0', STR_PAD_LEFT);
            $test[] = [
                'id'      => $id,
                '$padded' => $padded,
                'encoded' => $encoded = $this->encoder->encipher(Str::reverse($padded)),
                'decoded' => (int)Str::reverse($this->decoder->decipher($encoded)),
            ];
        }
        dd($test);
    }
}
