<?php

namespace Elegasoft\Cipher\Tests\Feature;

use Elegasoft\Cipher\Ciphers\Base62Cipher;

class ManualTest extends \Elegasoft\Cipher\Tests\CipherTestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function setCipher(): void
    {
        $this->encoder = new Base62Cipher(config('ciphers.keys.base62'));
        $this->decoder = clone $this->encoder;
    }

    public function it_has_perfect_cipher_accuracy()
    {
    }

    /** @test */
    public function it_can_work_on_a_specific_problem()
    {
        $encoded = $this->encoder->encode($text = '6&^.:K');
        $decoded = $this->decoder->decode($encoded);

        $this->assertSame($text, $decoded);
    }
}
